### ISSUE TITLE
AAT: Add _theme and _menu properties to sample course

### ISSUE THREAD

**Issue by swashbuck** [cgkineo/p101#4]
### Subject of the issue
The p101 course does not have the `_theme` and `_menu` properties as part of the _config.json_. This can cause issues when importing a course into the AAT.

Suggest adding:

```
  "_theme": "adapt-contrib-vanilla",
  "_menu": "adapt-contrib-boxMenu"
```
Same issue as https://github.com/adaptlearning/adapt_framework/issues/3602

**Comment by swashbuck** [comment]
@taylortom @joe-allen-89 Were there any other AAT v1 properties missing from the sample courses, or was this it?

**Comment by taylortom** [comment]
Is this definitely an issue? We should already have these same values when using the current [core schemas](https://github.com/adaptlearning/adapt-contrib-core/blob/master/schema%2Fconfig.schema.json#L21-L30)

**Comment by joe-allen-89** [comment]
@taylortom these missing attributes were causing issues with the v1 import. 

@swashbuck these were the only 2 added and it seemed to do the trick. Thank you.
